services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${FRONTEND_CONTAINER}
    restart: unless-stopped
    ports:
      - "${FRONTEND_EXT_PORT}:${FRONTEND_INT_PORT}"
    depends_on:
      - gateway
    networks:
      - app-network

networks:
  app-network:
    name: ${APP_NETWORK}
