name: blog-app

include:
  - path: gateway/compose.yml
  - path: frontend/compose.yml
  - path: services/user/compose.yml
  - path: services/content/compose.yml
  - path: services/search/compose.yml
  - path: services/ai/compose.yml
  - path: infrastructure/docker/shared/kafka.yml
  - path: infrastructure/docker/shared/logging.yml

networks:
  app-network:
    name: ${APP_NETWORK}
    driver: bridge
