name: topos-local

include:
  - path: kafka.yml
  - path: content-infra.yml
  - path: user-infra.yml
  - path: search-infra.yml
  - path: ../../../services/content/compose.local.yml
  - path: ../../../services/user/compose.local.yml
  - path: ../../../services/search/compose.local.yml
  - path: ../../../services/ai/compose.local.yml
  - path: ../../../gateway/compose.local.yml
  - path: ../../../frontend/compose.local.yml

networks:
  app-network:
    name: ${APP_NETWORK:-topos_local_network}
    driver: bridge
