services:
  gateway:
    build:
      context: ../
      dockerfile: gateway/Dockerfile
    container_name: ${GATEWAY_CONTAINER}
    restart: unless-stopped
    ports:
      - "${GATEWAY_EXT_PORT}:${GATEWAY_INT_PORT}"
    depends_on:
      - user-service
      - content-service
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: ${APP_NETWORK}
