services:
  gateway:
    build:
      context: ../
      dockerfile: gateway/Dockerfile
    container_name: gateway
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - content-service
    networks:
      - app-network