include:
  - path: infra/db.yml
  - path: infra/redis.yml

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${USER_SERVICE_CONTAINER}
    restart: unless-stopped
    ports:
      - "${USER_SERVICE_EXT_PORT}:${USER_SERVICE_INT_PORT}"
    environment:
      - REDIS_MASTER_NAME=${USER_REDIS_MASTER_NAME}
      - REDIS_SENTINELS=${USER_REDIS_SENTINEL_1_CONTAINER}:${USER_REDIS_SENTINEL_INT_PORT},${USER_REDIS_SENTINEL_2_CONTAINER}:${USER_REDIS_SENTINEL_INT_PORT},${USER_REDIS_SENTINEL_3_CONTAINER}:${USER_REDIS_SENTINEL_INT_PORT}
    depends_on:
      user-postgres-primary:
        condition: service_healthy
      user-redis-sentinel-1:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:${USER_SERVICE_INT_PORT}/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: ${APP_NETWORK}
