package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/kunalPisolkar24/topos/services/content/graph/model"
)

// FindPostByID is the resolver for the findPostByID field. In a
// request with batching enabled (WithBatching), all entities of the
// request share one repository lookup.
func (r *entityResolver) FindPostByID(ctx context.Context, id string) (*model.Post, error) {
	post, err := postByIDFrom(ctx, r.PostService, id)
	if err != nil {
		return nil, mapDomainError(err)
	}
	return mapDomainPostToModel(post), nil
}

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	return &model.User{ID: id}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
