package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"errors"

	"github.com/kunalPisolkar24/blogapp/services/content/graph/model"
	"github.com/kunalPisolkar24/blogapp/services/content/internal/middleware"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	userID, ok := ctx.Value(middleware.UserIDKey).(string)
	if !ok || userID == "" {
		return nil, errors.New("unauthorized")
	}

	var tags []string
	if input.Tags != nil {
		tags = append(tags, input.Tags...)
	}

	domainPost, err := r.PostService.CreatePost(ctx, input.Title, input.Body, userID, tags, input.ImageURL)
	if err != nil {
		return nil, err
	}

	return &model.Post{
		ID:        domainPost.ID,
		Title:     domainPost.Title,
		Body:      domainPost.Body,
		Slug:      domainPost.Slug,
		ImageURL:  domainPost.ImageUrl,
		Tags:      mapTags(domainPost.Tags),
		CreatedAt: domainPost.CreatedAt.String(),
		UpdatedAt: domainPost.UpdatedAt.String(),
		Author:    &model.User{ID: userID},
	}, nil
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, id string, input model.UpdatePostInput) (*model.Post, error) {
	userID, ok := ctx.Value(middleware.UserIDKey).(string)
	if !ok || userID == "" {
		return nil, errors.New("unauthorized")
	}

	existingPost, err := r.PostService.GetPost(ctx, id)
	if err != nil {
		return nil, errors.New("post not found")
	}

	if existingPost.AuthorID != userID {
		return nil, errors.New("forbidden")
	}

	var tags []string
	if input.Tags != nil {
		tags = append(tags, input.Tags...)
	}

	domainPost, err := r.PostService.UpdatePost(ctx, id, input.Title, input.Body, tags, input.ImageURL)
	if err != nil {
		return nil, err
	}

	return &model.Post{
		ID:        domainPost.ID,
		Title:     domainPost.Title,
		Body:      domainPost.Body,
		Slug:      domainPost.Slug,
		ImageURL:  domainPost.ImageUrl,
		Tags:      mapTags(domainPost.Tags),
		CreatedAt: domainPost.CreatedAt.String(),
		UpdatedAt: domainPost.UpdatedAt.String(),
		Author:    &model.User{ID: domainPost.AuthorID},
	}, nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (bool, error) {
	userID, ok := ctx.Value(middleware.UserIDKey).(string)
	if !ok || userID == "" {
		return false, errors.New("unauthorized")
	}

	existingPost, err := r.PostService.GetPost(ctx, id)
	if err != nil {
		return false, errors.New("post not found")
	}

	if existingPost.AuthorID != userID {
		return false, errors.New("forbidden")
	}

	if err := r.PostService.DeletePost(ctx, id); err != nil {
		return false, err
	}

	return true, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, page *int, limit *int) ([]*model.Post, error) {
	p := 1
	if page != nil {
		p = *page
	}
	l := 10
	if limit != nil {
		l = *limit
	}

	domainPosts, err := r.PostService.GetPosts(ctx, p, l)
	if err != nil {
		return nil, err
	}

	var posts []*model.Post
	for _, dp := range domainPosts {
		posts = append(posts, &model.Post{
			ID:        dp.ID,
			Title:     dp.Title,
			Body:      dp.Body,
			Slug:      dp.Slug,
			ImageURL:  dp.ImageUrl,
			Tags:      mapTags(dp.Tags),
			CreatedAt: dp.CreatedAt.String(),
			UpdatedAt: dp.UpdatedAt.String(),
			Author:    &model.User{ID: dp.AuthorID},
		})
	}
	return posts, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	dp, err := r.PostService.GetPost(ctx, id)
	if err != nil {
		return nil, err
	}
	return &model.Post{
		ID:        dp.ID,
		Title:     dp.Title,
		Body:      dp.Body,
		Slug:      dp.Slug,
		ImageURL:  dp.ImageUrl,
		Tags:      mapTags(dp.Tags),
		CreatedAt: dp.CreatedAt.String(),
		UpdatedAt: dp.UpdatedAt.String(),
		Author:    &model.User{ID: dp.AuthorID},
	}, nil
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context) ([]*model.Tag, error) {
	domainTags, err := r.TagService.GetTags(ctx)
	if err != nil {
		return nil, err
	}

	var tags []*model.Tag
	for _, dt := range domainTags {
		tags = append(tags, &model.Tag{
			ID:   dt.ID,
			Name: dt.Name,
		})
	}
	return tags, nil
}

// Posts is the resolver for the posts field.
func (r *userResolver) Posts(ctx context.Context, obj *model.User) ([]*model.Post, error) {
	domainPosts, err := r.PostService.GetPostsByAuthor(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	var posts []*model.Post
	for _, dp := range domainPosts {
		posts = append(posts, &model.Post{
			ID:        dp.ID,
			Title:     dp.Title,
			Body:      dp.Body,
			Slug:      dp.Slug,
			ImageURL:  dp.ImageUrl,
			Tags:      mapTags(dp.Tags),
			CreatedAt: dp.CreatedAt.String(),
			UpdatedAt: dp.UpdatedAt.String(),
			Author:    &model.User{ID: dp.AuthorID},
		})
	}
	return posts, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
