name: microservices-app

include:
  - path: shared/kafka.yml
  # - path: shared/logging.yml
  # - path: ../../gateway/compose.yml
  # - path: ../../frontend/compose.yml
  # - path: ../../services/user/compose.yml
  # - path: ../../services/content/compose.yml
  # - path: ../../services/summary/compose.yml
  - path: ../../services/search/compose.yml
  - path: ../../services/ai/compose.yml

networks:
  app-network:
    driver: bridge