services:
  user-service:
    build:
      context: ../../services/user
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    env_file:
      - ../../services/user/.env

  content-service:
    build:
      context: ../../services/content
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    env_file:
      - ../../services/content/.env

  gateway:
    build:
      context: ../../
      dockerfile: gateway/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - content-service