x-kafka-common: &kafka-common
  image: apache/kafka:3.7.0
  restart: always
  healthcheck:
    test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:${KAFKA_INT_PORT_1} --list"]
    interval: 10s
    timeout: 15s
    start_period: 20s
    retries: 5
  networks:
    - app-network
  deploy:
    resources:
      limits:
        cpus: '1'
        memory: 1G
      reservations:
        memory: 512M

services:
  kafka-1:
    <<: *kafka-common
    container_name: ${KAFKA_1_CONTAINER}
    hostname: kafka-1
    ports:
      - "${KAFKA_EXT_PORT_1}:${KAFKA_INT_PORT_1}"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:${KAFKA_INT_PORT_1},CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:${KAFKA_INT_PORT_1}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
    volumes:
      - kafka_1_data:/var/lib/kafka/data

  kafka-2:
    <<: *kafka-common
    container_name: ${KAFKA_2_CONTAINER}
    hostname: kafka-2
    ports:
      - "${KAFKA_EXT_PORT_2}:${KAFKA_INT_PORT_2}"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:${KAFKA_INT_PORT_2},CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:${KAFKA_INT_PORT_2}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
    volumes:
      - kafka_2_data:/var/lib/kafka/data

  kafka-3:
    <<: *kafka-common
    container_name: ${KAFKA_3_CONTAINER}
    hostname: kafka-3
    ports:
      - "${KAFKA_EXT_PORT_3}:${KAFKA_INT_PORT_3}"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:${KAFKA_INT_PORT_3},CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:${KAFKA_INT_PORT_3}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
    volumes:
      - kafka_3_data:/var/lib/kafka/data

  init-kafka:
    image: apache/kafka:3.7.0
    container_name: ${INIT_KAFKA_CONTAINER}
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:${KAFKA_INT_PORT_1} --list
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:${KAFKA_INT_PORT_1} --create --if-not-exists --topic ${KAFKA_TOPIC} --replication-factor 3 --partitions 6
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-1:${KAFKA_INT_PORT_1} --list
      "
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ${KAFKA_UI_CONTAINER}
    ports:
      - "${KAFKA_UI_EXT_PORT}:${KAFKA_UI_INT_PORT}"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: production-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_BROKERS}
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - app-network
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy

volumes:
  kafka_1_data:
  kafka_2_data:
  kafka_3_data:

networks:
  app-network:
    external: true
    name: ${APP_NETWORK}
