x-sentinel-common: &sentinel-common
  image: redis:7-alpine
  restart: unless-stopped
  command: >
    sh -c "echo 'port 26379' > /tmp/sentinel.conf &&
    echo 'sentinel monitor ${USER_REDIS_MASTER_NAME} ${USER_REDIS_MASTER_CONTAINER} 6379 2' >> /tmp/sentinel.conf &&
    echo 'sentinel down-after-milliseconds ${USER_REDIS_MASTER_NAME} 5000' >> /tmp/sentinel.conf &&
    echo 'sentinel failover-timeout ${USER_REDIS_MASTER_NAME} 10000' >> /tmp/sentinel.conf &&
    echo 'sentinel parallel-syncs ${USER_REDIS_MASTER_NAME} 1' >> /tmp/sentinel.conf &&
    echo 'sentinel resolve-hostnames yes' >> /tmp/sentinel.conf &&
    redis-sentinel /tmp/sentinel.conf"
  networks:
    - app-network
  depends_on:
    user-redis-master:
      condition: service_healthy
    user-redis-replica:
      condition: service_healthy
  healthcheck:
    test: ["CMD", "redis-cli", "-p", "${USER_REDIS_SENTINEL_INT_PORT}", "ping"]
    interval: 10s
    timeout: 5s
    retries: 5

services:
  user-redis-master:
    image: redis:7-alpine
    container_name: ${USER_REDIS_MASTER_CONTAINER}
    restart: unless-stopped
    command: redis-server --appendonly yes --repl-diskless-load on-empty-db --repl-diskless-sync yes
    volumes:
      - redis_master_data:/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user-redis-replica:
    image: redis:7-alpine
    container_name: ${USER_REDIS_REPLICA_CONTAINER}
    restart: unless-stopped
    command: redis-server --replicaof ${USER_REDIS_MASTER_CONTAINER} 6379 --appendonly yes --repl-diskless-load on-empty-db --repl-diskless-sync yes
    volumes:
      - redis_replica_data:/data
    depends_on:
      user-redis-master:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user-redis-sentinel-1:
    <<: *sentinel-common
    container_name: ${USER_REDIS_SENTINEL_1_CONTAINER}
    ports:
      - "${USER_REDIS_SENTINEL_EXT_PORT}:${USER_REDIS_SENTINEL_INT_PORT}"

  user-redis-sentinel-2:
    <<: *sentinel-common
    container_name: ${USER_REDIS_SENTINEL_2_CONTAINER}

  user-redis-sentinel-3:
    <<: *sentinel-common
    container_name: ${USER_REDIS_SENTINEL_3_CONTAINER}

networks:
  app-network:
    external: true
    name: ${APP_NETWORK}

volumes:
  redis_master_data:
  redis_replica_data:
