services:
  content-mongo-1:
    image: mongo:7.0
    container_name: ${CONTENT_MONGO_1_CONTAINER}
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "${CONTENT_MONGO_INT_PORT}" ]
    ports:
      - "${CONTENT_MONGO_EXT_PORT}:${CONTENT_MONGO_INT_PORT}"
    volumes:
      - content_mongo1_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'${CONTENT_MONGO_1_CONTAINER}:${CONTENT_MONGO_INT_PORT}'},{_id:1,host:'${CONTENT_MONGO_2_CONTAINER}:${CONTENT_MONGO_INT_PORT}'},{_id:2,host:'${CONTENT_MONGO_3_CONTAINER}:${CONTENT_MONGO_INT_PORT}'}]}) }" | mongosh --port ${CONTENT_MONGO_INT_PORT} --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

  content-mongo-2:
    image: mongo:7.0
    container_name: ${CONTENT_MONGO_2_CONTAINER}
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "${CONTENT_MONGO_INT_PORT}" ]
    volumes:
      - content_mongo2_data:/data/db
    networks:
      - app-network

  content-mongo-3:
    image: mongo:7.0
    container_name: ${CONTENT_MONGO_3_CONTAINER}
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "${CONTENT_MONGO_INT_PORT}" ]
    volumes:
      - content_mongo3_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: ${APP_NETWORK}

volumes:
  content_mongo1_data:
  content_mongo2_data:
  content_mongo3_data:
