// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/ai/ai_service.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentRequest) Reset() {
	*x = ContentRequest{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentRequest) ProtoMessage() {}

func (x *ContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentRequest.ProtoReflect.Descriptor instead.
func (*ContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *ContentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentResponse) Reset() {
	*x = ContentResponse{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentResponse) ProtoMessage() {}

func (x *ContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentResponse.ProtoReflect.Descriptor instead.
func (*ContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *ContentResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextRequest) Reset() {
	*x = ContextRequest{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextRequest) ProtoMessage() {}

func (x *ContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextRequest.ProtoReflect.Descriptor instead.
func (*ContextRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{2}
}

func (x *ContextRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContextRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type TagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagsResponse) Reset() {
	*x = TagsResponse{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsResponse) ProtoMessage() {}

func (x *TagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsResponse.ProtoReflect.Descriptor instead.
func (*TagsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{3}
}

func (x *TagsResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PostGenerationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostGenerationRequest) Reset() {
	*x = PostGenerationRequest{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostGenerationRequest) ProtoMessage() {}

func (x *PostGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostGenerationRequest.ProtoReflect.Descriptor instead.
func (*PostGenerationRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{4}
}

func (x *PostGenerationRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type PostGenerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostGenerationResponse) Reset() {
	*x = PostGenerationResponse{}
	mi := &file_proto_ai_ai_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostGenerationResponse) ProtoMessage() {}

func (x *PostGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostGenerationResponse.ProtoReflect.Descriptor instead.
func (*PostGenerationResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_service_proto_rawDescGZIP(), []int{5}
}

func (x *PostGenerationResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostGenerationResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PostGenerationResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PostGenerationResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_proto_ai_ai_service_proto protoreflect.FileDescriptor

const file_proto_ai_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/ai/ai_service.proto\x12\x02ai\"$\n" +
	"\x0eContentRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"+\n" +
	"\x0fContentResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\":\n" +
	"\x0eContextRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"\"\n" +
	"\fTagsResponse\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"/\n" +
	"\x15PostGenerationRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"p\n" +
	"\x16PostGenerationResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags2\xc4\x01\n" +
	"\tAIService\x12:\n" +
	"\x0fGenerateSummary\x12\x12.ai.ContentRequest\x1a\x13.ai.ContentResponse\x124\n" +
	"\fGenerateTags\x12\x12.ai.ContextRequest\x1a\x10.ai.TagsResponse\x12E\n" +
	"\fGeneratePost\x12\x19.ai.PostGenerationRequest\x1a\x1a.ai.PostGenerationResponseB>Z<github.com/kunalPisolkar24/blogapp/services/content/proto/aib\x06proto3"

var (
	file_proto_ai_ai_service_proto_rawDescOnce sync.Once
	file_proto_ai_ai_service_proto_rawDescData []byte
)

func file_proto_ai_ai_service_proto_rawDescGZIP() []byte {
	file_proto_ai_ai_service_proto_rawDescOnce.Do(func() {
		file_proto_ai_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_ai_service_proto_rawDesc), len(file_proto_ai_ai_service_proto_rawDesc)))
	})
	return file_proto_ai_ai_service_proto_rawDescData
}

var file_proto_ai_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_ai_ai_service_proto_goTypes = []any{
	(*ContentRequest)(nil),         // 0: ai.ContentRequest
	(*ContentResponse)(nil),        // 1: ai.ContentResponse
	(*ContextRequest)(nil),         // 2: ai.ContextRequest
	(*TagsResponse)(nil),           // 3: ai.TagsResponse
	(*PostGenerationRequest)(nil),  // 4: ai.PostGenerationRequest
	(*PostGenerationResponse)(nil), // 5: ai.PostGenerationResponse
}
var file_proto_ai_ai_service_proto_depIdxs = []int32{
	0, // 0: ai.AIService.GenerateSummary:input_type -> ai.ContentRequest
	2, // 1: ai.AIService.GenerateTags:input_type -> ai.ContextRequest
	4, // 2: ai.AIService.GeneratePost:input_type -> ai.PostGenerationRequest
	1, // 3: ai.AIService.GenerateSummary:output_type -> ai.ContentResponse
	3, // 4: ai.AIService.GenerateTags:output_type -> ai.TagsResponse
	5, // 5: ai.AIService.GeneratePost:output_type -> ai.PostGenerationResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ai_ai_service_proto_init() }
func file_proto_ai_ai_service_proto_init() {
	if File_proto_ai_ai_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_ai_service_proto_rawDesc), len(file_proto_ai_ai_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_ai_service_proto_goTypes,
		DependencyIndexes: file_proto_ai_ai_service_proto_depIdxs,
		MessageInfos:      file_proto_ai_ai_service_proto_msgTypes,
	}.Build()
	File_proto_ai_ai_service_proto = out.File
	file_proto_ai_ai_service_proto_goTypes = nil
	file_proto_ai_ai_service_proto_depIdxs = nil
}
