input {
  beats {
    port => 5044
  }
}

filter {
  if [container][labels][com_docker_compose_service] {
    
    mutate {
      add_field => { "service" => "%{[container][labels][com_docker_compose_service]}" }
    }

    if [service] == "backend" {
      json {
        source => "message"
      }
    } 
    else {
      json {
        source => "message"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "filebeat-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}